// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://swagger.io/terms/",
        "contact": {
            "name": "İbrahim Can Mercan",
            "email": "imrcn77@mail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
		"/v1/user": {
            "get": {
				"tags": [
                    "Generate"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/v1/credit_card": {
            "get": {
				"tags": [
                    "Generate"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CreditCard"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
		"/v1/address": {
            "get": {
				"tags": [
                    "Generate"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Address"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
		"User": {
            "type": "object",
            "properties": {
                "gender": {
                    "type": "string"
                },
				"name": {
				   "type": "object",
                    "properties": {
                        "fullName": {
                            "type": "string"
                        },
                        "firstName": {
                            "type": "string"
                        },
                        "lastName": {
                            "type": "string"
                        }
                    }
                },
				"login": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "uuid": {
                            "type": "string"
                        },
                  		"username": {
                            "type": "string"
                        },
                  		"email": {
                            "type": "string"
                        },
                        "password": {
                            "type": "string"
                        },
                        "password_hash": {
                            "type": "object",
                            "properties": {
                                "md5": {
                                    "type": "string"
                                },
                                "sha1": {
                                    "type": "string"
                                },
                                "sha256": {
                                    "type": "string"
                                },
                                "sha512": {
                                    "type": "string"
                                }
                            }
                        },
                        "phoneNumber": {
                            "type": "string"
                        },
                        "role": {
                            "type": "string"
                        },
                        "user_agent": {
                            "type": "object",
                            "properties": {
                                "chrome": {
                                    "type": "string"
                                },
                                "firefox": {
                                    "type": "string"
                                },
                                "opera": {
                                    "type": "string"
                                },
                                "safari": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
            	"birthDate": {
                    "type": "string"
                },
                "registeredDate": {
                    "type": "string"
                },
                "macAddress": {
                    "type": "string"
                },
            	"ip_address": {
                    "type": "object",
                    "properties": {
                        "v4": {
                            "type": "string"
                        },
                        "v6": {
                            "type": "string"
                        }
                    }
                },
            	"location": {
                    "type": "object",
                    "properties": {
                        "country": {
                            "type": "string"
                        },
                        "city": {
                            "type": "string"
                        },
                        "state": {
                            "type": "string"
                        },
                        "street": {
                            "type": "string"
                        },
                        "zipCode": {
                            "type": "integer"
                        },
                        "coordinates": {
                            "type": "object",
                            "properties": {
                                "latitude": {
                                    "type": "number"
                                },
                                "longitude": {
                                    "type": "number"
                                }
                            }
                        },
                        "timeZone": {
                            "type": "string"
                        }
                    }
                },
            	"credit_card": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string"
                        },
                        "number": {
                            "type": "string"
                        },
                        "exp": {
                            "type": "string"
                        },
                        "cvv": {
                            "type": "string"
                        }
                    }
                },
            	"bitcoin": {
                    "type": "object",
                    "properties": {
                        "address": {
                            "type": "string"
                        },
                        "privateKey": {
                            "type": "string"
                        }
                    }
                },
            	"company": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "suffix": {
                            "type": "string"
                        },
                        "job": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string"
                                },
                                "level": {
                                    "type": "string"
                                },
                                "descriptor": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "size": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
            	"createdAt": {
                    "type": "string"
                }
            }
        },
		"CreditCard": {
            "type": "object",
            "properties": {
				"id": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                },
                "credit_card": {
                    "type": "object",
                    "properties": {
                        "cvv": {
                            "type": "string"
                        },
                        "exp": {
                            "type": "string"
                        },
                        "number": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        }
                    }
                },
				"createdAt": {
                    "type": "string"
                }
            }
        },
		"Address": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
				"uuid": {
                    "type": "string"
                },
                "location": {
                    "type": "object",
                    "properties": {
                        "country": {
                            "type": "string"
                        },
						"city": {
                            "type": "string"
                        },
                        "state": {
                            "type": "string"
                        },
                        "street": {
                            "type": "string"
                        },
						"zipCode": {
                            "type": "integer"
                        },
						"coordinates": {
                            "type": "object",
                            "properties": {
                                "latitude": {
                                    "type": "number"
                                },
                                "longitude": {
                                    "type": "number"
                                }
                            }
                        },
                        "timeZone": {
                            "type": "string"
                        }
                    }
                },
				"createdAt": {
                    "type": "string"
                }
            }
        },
		"Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "gorandomusergenerator.herokuapp.com",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Go Random User Generator",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
