swagger: "2.0"
info:
  contact:
    email: imrcn77@mail.com
    name: İbrahim Can Mercan
  termsOfService: https://swagger.io/terms/
  title: Go Random User Generator
  version: 1.0.0
basePath: /api
schemes:
  - http
  - https
host: gorandomusergenerator.herokuapp.com
definitions:
  User:
    type: object
    properties:
      gender:
        type: string
      name:
        type: object
        properties:
          fullName:
            type: string
          firstName:
            type: string
          lastName:
            type: string
      login:
        type: object
        properties:
          id:
            type: integer
          uuid:
            type: string
          username:
            type: string
          email:
            type: string
          password:
            type: string
          password_hash:
            type: object
            properties:
              md5:
                type: string
              sha1:
                type: string
              sha256:
                type: string
              sha512:
                type: string
          phoneNumber:
            type: string
          role:
            type: string
          user_agent:
            type: object
            properties:
              chrome:
                type: string
              firefox:
                type: string
              opera:
                type: string
              safari:
                type: string
      birthDate:
        type: string
      registeredDate:
        type: string
      macAddress:
        type: string
      ip_address:
        type: object
        properties:
          v4:
            type: string
          v6:
            type: string
      location:
        type: object
        properties:
          country:
            type: string
          city:
            type: string
          state:
            type: string
          street:
            type: string
          zipCode:
            type: integer
          coordinates:
            type: object
            properties:
              latitude:
                type: number
              longitude:
                type: number
          timeZone:
            type: string
      credit_card:
        type: object
        properties:
          type:
            type: string
          number:
            type: string
          exp:
            type: string
          cvv:
            type: string
      bitcoin:
        type: object
        properties:
          address:
            type: string
          privateKey:
            type: string
      company:
        type: object
        properties:
          name:
            type: string
          suffix:
            type: string
          job:
            type: object
            properties:
              title:
                type: string
              level:
                type: string
              descriptor:
                type: string
      size:
        type: string
      rating:
        type: number
      createdAt:
        type: string
  CreditCard:
    type: object
    properties:
      id:
        type: integer
      uuid:
        type: string
      credit_card:
        type: object
        properties:
          type:
            type: string
          number:
            type: string
          exp:
            type: string
          cvv:
            type: string
  Address:
    type: object
    properties:
      id:
        type: integer
      uuid:
        type: string
      location:
        type: object
        properties:
          country:
            type: string
          city:
            type: string
          state:
            type: string
          street:
            type: string
          zipCode:
            type: integer
          coordinates:
            type: object
            properties:
              latitude:
                type: number
              longitude:
                type: number
          timeZone:
            type: string
  Response:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
paths:
  /v1/user:
    get:
      tags:
        - Generate
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
  /v1/credit_card:
    get:
      tags:
        - Generate
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CreditCard'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
  /v1/address:
    get:
      tags:
        - Generate
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Address'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'